### ISSUE TITLE
prompt to toolcall

### ISSUE THREAD

**Issue by bincooo** [LouisShark/chatgpt_system_prompt#108]
Sorry, I am not familiar with English, here is the machine translation:
Can you design a prompt so that AI without toolcall capability can have it?
For example:

```
## Tools
You can use these tools below:
1. [website-crawler____getWebsiteContent] Used to parse web content.
	parameters:
		url: {
			type: String
			description: Web link
		}
2. [website-crawler____getWeather] It is used to obtain weather information about the destination area.
	parameters:
		city: {
			type: String
			description: City name
		}
##

## conversation history
... ...
##


Output:
type ID=
params JSON=
```

thank you.

**Comment by 0xeb** [comment]
hello @bincooo , sorry we are not able to help, but this repository is not for GPT design support.

--
你好 @bincooo，很抱歉我们无法提供帮助，但这个仓库不是用于GPT设计支持的。
