### ISSUE TITLE
relation to TheBigPromptLibrary

### ISSUE THREAD

**Issue by normster** [LouisShark/chatgpt_system_prompt#113]
Hi,

I was just wondering what the relationship between this repo and https://github.com/0xeb/TheBigPromptLibrary is supposed to be. It looks like there is a lot of overlap in prompts of GPTs from the ChatGPT store.

**Comment by LouisShark** [comment]
https://github.com/0xeb/TheBigPromptLibrary  is forked from this repo, and Elias is my collaborator，he wants to do more on this, finally we have two repo

**Comment by normster** [comment]
Gotcha, thanks. Just wanted to clarify for proper attribution.

**Comment by 0xeb** [comment]
@normster , best attribution if you track the commit author as well / commit hash
