### ISSUE TITLE
Make it clear that protection is impossible

### ISSUE THREAD

**Issue by 3rd** [LouisShark/chatgpt_system_prompt#16]
Hey, the readme gives the impression that it's possible to protect one's GPT by prompting, but it's not.
No amount of prompting will be safe. Not even GPTs made with the sole purpose of not disclosing their instructions are safe.
I've seen a lot of people adding these junk protection prompts: https://andrei.fyi/blog/reverse-engineering-gpts
And apart from not working, adding something like this pollutes the context and results in lower quality output.

**Comment by LouisShark** [comment]
Yes, if the llm can strictly execute the instructions, it doesn't have to be so troublesome，Even if you design a lot of anti-reverse prompts，the llm have Hallucination， But it will raise the threshold for others to get the prompt.
